name: Test

on:
  push:
    branches: [ main, add-testing ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

    - name: Build and Test
      run: |
        xcodebuild test -scheme MenuBarApp -destination 'platform=macOS' \
          -resultBundlePath ./TestResults.xcresult \
          -derivedDataPath ./DerivedData
      continue-on-error: true
    
    - name: Publish test results
      uses: kishikawakatsumi/xcresulttool@v1
      if: success() || failure()
      with:
        path: TestResults.xcresult
        token: ${{ secrets.GITHUB_TOKEN }}
        show-passed-tests: false
        show-code-coverage: false
        upload-bundles: never