name: Test

on:
  push:
    branches: [ main, add-testing ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

    - name: Build and Test
      run: xcodebuild test -scheme MenuBarApp -destination 'platform=macOS'