name: Test

on:
  push:
    branches: [ main, add-testing ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: swift build -v

    - name: Run tests
      run: ./.build/debug/MenuBarAppTests